services:
  db:
    image: mysql:8.0
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: betterpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: betterwppass
    ports:
      - "3306:3306"

  wordpress:
    build:
        context: .
        dockerfile: docker/Dockerfile
    container_name: wp-site
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: betterwppass
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
